sudo: required
language: node_js
node_js: 8
cache:
  directories:
  - node_modules
addons:
  apt:
    update: true
    packages:
    - calibre
    - xvfb
before_install:
- npm install -g gitbook-cli
- echo '#!/bin/bash' >> $HOME/bin/ebook-convert
- echo 'xvfb-run /usr/bin/ebook-convert "$@"' >> $HOME/bin/ebook-convert
- chmod a+x $HOME/bin/ebook-convert
install:
- gitbook install
script:
- gitbook build
- gitbook pdf
- gitbook epub
- gitbook mobi
- cp -fv ./book.pdf ./_book/book.pdf
- cp -fv ./book.epub ./_book/book.epub
- cp -fv ./book.mobi ./_book/book.epub
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: "./_book"
  on:
    branch: master
- provider: releases
  skip-cleanup: true
  api_key: "$GITHUB_TOKEN"
  file:
  - _book/book.pdf
  - _book/book.epub
  - _book/book.mobi
  on:
    tags: true
env:
  global:
    secure: XMH/GfbaFtgl5qMOQZjTq+HhvbM/gmWRmetG2XZto/aE7JBLjsax5KQduYc6xIvlUvoIqg/JkHO81vZvzJUWroNc79x72XihNBNGGhjluoozDkkPF1GYktDUrOiTDSgJvM7Swm7MsKNOKKpHPrOzYZJDWepMZhzvntC5xgK/ZW343+cPDMrLTbFol5r4oI4cr9tAZoSHiZU71Q1pY/btWhsDw8/Dw4eazgWXmvKHzAJn8IQqw7aZA5e2CA4YITa8SXcjSTA9SXN5DufXDANNbJ+JjAWhnSUyekfPfIarrxO/NQz96THs/vTVlor9yE87MAzh+0afBHsdXViNIclnC75K/IWgSz1R1G0lHOHgItOxxjNwKJI7T6EEFdWSZEz1eDlbAfY0FHRiOXaETtFqKX1AkqX+XzvXgoG40oT/iO2NZbLl+NjMbCyPayNTssaptd2ZWs73AikASdfV7i5ACbEI1rNsoiGDWF4FWtKaIZl8l0mOS4FC/7Md1R7E5zAsXdjIec4IzbMhFGlHv7V13T74PZKQoP2aE9zv5qmDR1uW8xhDMw4fu7ebWnKhaId1rMeVisg34BUF8opjfv+Xg8YwzIrCgOLUMQcwPPEHfx6rXrD2NWuhjq7iI5GFvLXtBMAznP5ZtYaey9EKORdQJs/RzFSWUr0hj4iCdotCSf4=
